### ISSUE TITLE
Added a few custom tweaks in my fork

### ISSUE THREAD

**Issue by BlackScreen** [agentspooky/fix-pal#4]
Hey there,
I hope it was ok to push the pull requests.
I have added two big changes to my fork: https://github.com/BlackScreen/fix-pal/pull/4
Maybe there is something in there which you can and will use also. I did not want to push that a pull request.
Thanks so much for your script, it helped me big time!

**Comment by agentspooky** [comment]
Hi, thanks for reaching out! I'm so sorry I didn't notice this sooner. I *think* I've got my GitHub notification settings fixed now, so with any luck I won't be *quite* so late to respond in the future.

I'm absolutely thrilled you found my script helpful. I've gone ahead and merged one of your PRs, and I'll be updating mine to support filenames with spaces very soon. (Details on why I'm doing it on my own are in the relevant PR.) Cheers!
